# Generated by Django 4.0.3 on 2022-04-20 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion_board_for_lecture',
            name='lecture_id',
            field=models.ManyToManyField(related_name='discuss', to='elearning.lecture'),
        ),
        migrations.AlterField(
            model_name='discussion_board_for_lecture',
            name='username',
            field=models.ManyToManyField(related_name='active', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questions',
            name='lecture_id',
            field=models.ManyToManyField(related_name='asks', to='elearning.lecture'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='lesson_id',
            field=models.ManyToManyField(blank=True, related_name='questions', to='elearning.lesson'),
        ),
        migrations.CreateModel(
            name='Lessonstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, null=True)),
                ('course_id', models.ManyToManyField(related_name='course', to='elearning.course')),
                ('lecture_id', models.ManyToManyField(related_name='lecture', to='elearning.lecture')),
                ('lesson_id', models.ManyToManyField(related_name='lesson', to='elearning.lesson')),
                ('student', models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
