# Generated by Django 4.0.3 on 2022-04-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_alter_discussion_board_for_lecture_lecture_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion_board_for_lecture',
            old_name='username',
            new_name='user_id',
        ),
    ]
