# Generated by Django 4.0.3 on 2022-04-20 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_rename_username_discussion_board_for_lecture_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='activity',
            field=models.ManyToManyField(related_name='activity', to=settings.AUTH_USER_MODEL),
        ),
    ]
