# Generated by Django 4.0.3 on 2022-05-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0006_assignment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_project',
            name='title',
            field=models.TextField(default='Final', max_length=100),
        ),
        migrations.AlterField(
            model_name='final_project',
            name='course_id',
            field=models.ManyToManyField(related_name='final', to='elearning.course'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='doc_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option3',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option4',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
