# Generated by Django 4.0.3 on 2022-05-16 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0007_final_project_title_alter_final_project_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_project',
            name='title',
            field=models.CharField(default='Final', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonstatus',
            name='student',
            field=models.ManyToManyField(related_name='userstatus', to=settings.AUTH_USER_MODEL),
        ),
    ]
