# Generated by Django 4.0.3 on 2022-05-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0009_assignment_submission_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_submission',
            name='answer',
            field=models.CharField(max_length=1000),
        ),
    ]
