# Generated by Django 4.0.3 on 2022-05-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0010_alter_assignment_submission_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_submission',
            name='grade',
            field=models.IntegerField(blank=True),
        ),
    ]
