# Generated by Django 4.0.3 on 2022-05-26 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0015_final_submission_create_alter_final_submission_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_submission',
            name='grade',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='final_submission',
            name='answer',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='final_submission',
            name='grade',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert', models.FileField(upload_to='')),
                ('grade', models.IntegerField(blank=True, default=-1)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('course_id', models.ManyToManyField(to='elearning.course')),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
