# Generated by Django 4.0.3 on 2022-05-26 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0016_alter_assignment_submission_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grade',
        ),
        migrations.AlterField(
            model_name='grade',
            name='cert',
            field=models.FileField(blank=True, null=True, upload_to='course/cert/'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='course_id',
            field=models.ManyToManyField(related_name='graduated', to='elearning.course'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='user_id',
            field=models.ManyToManyField(related_name='grade_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
