# Generated by Django 4.0.3 on 2022-05-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0017_remove_grade_grade_alter_grade_cert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='course_id',
        ),
        migrations.AddField(
            model_name='grade',
            name='final_id',
            field=models.ManyToManyField(related_name='graduated', to='elearning.final_submission'),
        ),
    ]
