# Generated by Django 4.0.3 on 2022-05-27 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0019_grade_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.URLField(default='https://via.placeholder.com/150x150/FFFF00/000000/?text=User+IMG', null=True),
        ),
        migrations.CreateModel(
            name='Assignment_tatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, null=True)),
                ('assignment_id', models.ManyToManyField(blank=True, related_name='assignment_status', to='elearning.assignment')),
                ('course_id', models.ManyToManyField(related_name='course_assignments', to='elearning.course')),
                ('lecture_id', models.ManyToManyField(blank=True, related_name='lecture_status', to='elearning.lecture')),
                ('student', models.ManyToManyField(related_name='complete', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
