# Generated by Django 4.0.3 on 2022-05-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0020_alter_user_image_assignment_tatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignment_tatus',
            new_name='Assignment_status',
        ),
    ]
