from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name='index'),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("profile/<int:id>", views.profile, name="profile"),
    path("editprofile/<int:id>", views.editprofile, name="editprofile"),
    # path("course", views.course, name="course"),
    path("course/<int:id>", views.course, name="course"),
    path("enroll/<int:id>", views.enroll, name="enroll"),
    # path("lectures", views.lectures, name="lecture"),
    path("lectures/<int:id>", views.lectures, name="lectures"),
    path("loadlesson", views.loadlesson, name="loadlesson"),
    path("filter", views.filltercourses, name="filltercourses"),
    path("addcourse", views.addcourse, name="addcourse"),
    path("editcourse/<int:id>", views.editcourse, name="editcourse"),
    path("delcourse/<int:id>", views.delcourse, name="delcourse"),
    path("addlecture", views.addlecture, name="addlecture"),
    path("editlecture/<int:cid>/<int:lid>",
         views.editlecture, name="editlecture"),
    path("addlecturejson", views.addlecturejson, name="addlecturejson"),
    path("dellecture/<int:cid>/<int:lid>", views.dellecture, name="dellecture"),
    path("addlesson", views.addlesson, name="addlesson"),
    path("editlesson/<int:cid>/<int:lid>/<int:lesonid>",
         views.editlesson, name="editlesson"),
    path("dellesson/<int:cid>/<int:lid>/<int:lesonid>",
         views.dellesson, name="dellesson"),
    path("addquestion", views.addquestion, name="addquestion"),
    path("editquestion/<int:qid>", views.editquestion, name="editquestion"),
    path("delquestion/<int:qid>", views.delquestion, name="delquestion"),
    path("addassigne", views.addassigne, name="addassigne"),
    path("assigne", views.assigne, name="assigne"),
    path("editassigne/<int:id>", views.editassigne, name="editassigne"),
    path("delassigne/<int:id>", views.delassigne, name="delassigne"),
    path("managefinal/<int:id>", views.managefinal, name="managefinal"),
    path("manage/<int:id>", views.manage, name="manage"),
    path("completestatus", views.completestatus, name="completestatus"),
    path("loadfinal", views.loadfinal, name="loadfinal"),
    path("submitassigne", views.submitassigne, name="submitassigne"),
    path("submitfinal", views.submitfinal, name="submitfinal"),
    #path("change", views.change, name="change"),
    path("gradeassigne/<int:a_id>/<int:s_id>",
         views.gradeassigne, name="gradeassigne"),
    path("gradefinal/<int:f_id>/<int:fs_id>",
         views.gradefinal, name="gradefinal"),
    path("upload_cert/<int:c_id>/<int:u_id>",
         views.upload_cert, name="upload_cert"),
    path("grade/<int:c_id>/<int:u_id>", views.grade, name="grade"),
    path("addreview/<int:id>", views.addreview, name="addreview"),
    path("addcomment/<int:c_id>/<int:l_id>",
         views.addcomment, name="addcomment"),
    # path("addlessonjson", views.addlessonjson, name="addlessonjson"),
    # path("lectures/<int:id>", views.loadlectures, name="loadlectures"),
]
